### ISSUE TITLE
Binary Encoding problem

### ISSUE THREAD

**Issue by yzard** [wdm0006/categorical_encoding#3]
Hi, there, first time using this binary encoding method, but I think there is a bug:

- When encoding a column contained 3 possible categories, it encodes as 1 columns
- When encoding a column contained 5 possible categories, it encodes as 2 columns
- same thing you can find in 9 possible categories, only encoded as 3 columns
- Also when encoding a column contained only 2 possible categories, it returns empty DataFrame

2 categories:
```
>>> import pandas as pd
>>> import category_encoders as ce
>>> df1 = pd.DataFrame([[1],[2],[2],[1]], columns=['col_a'])
>>> df1
   col_a
0      1
1      2
2      2
3      1
>>> encoder = ce.BinaryEncoder(cols=['col_a'])
>>> encoder.transform(df1)
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]
```
3 categories:
```
>>> df2 = pd.DataFrame([[1],[2],[2],[3]], columns=['col_a'])
>>> encoder.transform(df2)
   col_a_0
0        0
1        1
2        1
3        1
```

**Comment by wdm0006** [comment]
Thanks for opening up an issue, it looks like you're right, I think there is an off-by-one error in line 37 of binary.py, so we are ending up with one too few columns.

If you're interested in trying to do a fix and adding a test for this case into the test suite I'd be happy to help you out and merge it in, otherwise I'll fix it and cut a new release this week.

**Comment by yzard** [comment]
Hi, Will,

I'm currently working on a pretty big project, kind lack of time to do that, you can fix it and release it this time, If I found some other bugs and have time, I will try to contribute this.

Regards,
Zhuo Yin

**Comment by wdm0006** [comment]
No worries, I'll ping you when it's released. Thanks again
